"use client"

import { BookOpen, CalendarDays, Link2, Plus, Unlink } from "lucide-react"
import type { UniverseEra } from "../lib/chronology"
import { formatFictionalYear, resolveEra } from "../lib/chronology"
import type { CampaignRecord, KnowledgePage } from "../lib/knowledge-model"
import { SubpageHeader } from "./subpage-header"

export function CampaignStory({ campaign, stories, allStories, pages, eras, onCreate, onLink, onUnlink, onOpenStory, onBack = () => { if (typeof window !== "undefined") window.history.back() } }: { campaign: CampaignRecord; stories: KnowledgePage[]; allStories: KnowledgePage[]; pages: KnowledgePage[]; eras: UniverseEra[]; onCreate: () => void; onLink: (id: string) => void; onUnlink: (id: string) => void; onOpenStory: (story: KnowledgePage) => void; onBack?: () => void }) {
  const events = stories.flatMap((story) => story.storyEventIds.map((id) => ({ story, event: pages.find((page) => page.id === id) })).filter((item): item is { story: KnowledgePage; event: KnowledgePage } => Boolean(item.event))).sort((left, right) => (left.event.eventYear ?? Number.POSITIVE_INFINITY) - (right.event.eventYear ?? Number.POSITIVE_INFINITY))
  const groups = new Map<string, typeof events>()
  for (const item of events) {
    const era = resolveEra(item.event.eventYear, eras, item.event.eraId)
    const key = era?.id ?? "unassigned"
    groups.set(key, [...(groups.get(key) ?? []), item])
  }
  return <section className="campaign-subpage campaign-story-panel"><SubpageHeader title="História da campanha" onBack={onBack} /><header className="campaign-subpage-heading"><div><p className="eyebrow">{campaign.title || "Campanha sem nome"}</p><h2>Histórias vinculadas</h2><p>Crie uma História da Wiki sem sair da campanha ou vincule uma existente.</p></div><button className="primary-button" onClick={onCreate}><Plus size={16} /> Criar História</button></header><div className="subpage-actions"><label><span>Vincular História existente</span><select defaultValue="" onChange={(event) => { if (event.target.value) onLink(event.target.value); event.currentTarget.value = "" }}><option value="">Escolha uma História…</option>{allStories.filter((story) => !stories.some((linked) => linked.id === story.id)).map((story) => <option key={story.id} value={story.id}>{story.title || "História sem nome"}</option>)}</select></label><span className="subpage-count"><BookOpen size={15} /> {stories.length} vinculada{stories.length === 1 ? "" : "s"}</span></div>{stories.length > 0 && <div className="linked-story-list">{stories.map((story) => <article key={story.id}><button onClick={() => onOpenStory(story)}><BookOpen size={19} /><span><strong>{story.title || "História sem nome"}</strong><small>{story.storyEventIds.length} acontecimento{story.storyEventIds.length === 1 ? "" : "s"}</small></span></button><button className="icon-button" onClick={() => onUnlink(story.id)} aria-label={`Desvincular ${story.title}`}><Unlink size={15} /></button></article>)}</div>}{events.length > 0 ? <div className="campaign-chronology"><header><h3>Cronologia agregada</h3><span>{events.length} acontecimentos</span></header>{[...groups.entries()].map(([key, items]) => <section key={key}><h4>{key === "unassigned" ? "Sem era definida" : eras.find((era) => era.id === key)?.name ?? "Era"}</h4>{items.map(({ story, event }) => <button key={`${story.id}-${event.id}`} onClick={() => onOpenStory(story)}><CalendarDays size={14} /><span>{event.eventYear != null ? formatFictionalYear(event.eventYear, resolveEra(event.eventYear, eras, event.eraId)?.calendar) : "Ano não definido"}</span><strong>{event.title || "Acontecimento sem nome"}</strong><small>{story.title || "História sem nome"}</small></button>)}</section>)}</div> : <div className="knowledge-empty"><Link2 size={28} /><strong>Nenhum acontecimento agregado.</strong><p>Adicione acontecimentos nas histórias vinculadas para formar a cronologia da campanha.</p></div>}</section>
}
