"use client"
import { useMemo, useState } from "react"
import { Clock3, Pencil, Plus, Trash2 } from "lucide-react"
import type { KnowledgePage } from "../lib/knowledge-model"
import { formatCalendarYears, parseCalendarYear } from "../lib/chronology"

export function EraManager({ eras, events, onOpen, onCreate, onSave, onDelete }: { eras: KnowledgePage[]; events: KnowledgePage[]; onOpen?: (era: KnowledgePage) => void; onCreate?: () => void; onSave?: (era: KnowledgePage) => void; onDelete?: (id: string) => void }) {
  const [editing, setEditing] = useState<KnowledgePage | null>(null)
  const counts = useMemo(() => new Map(eras.map((era) => [era.id, events.filter((event) => event.tags.some((tag) => tag.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("pt-BR") === era.title.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("pt-BR"))).length])), [eras, events])
  if (editing) return <EraForm era={editing} onCancel={() => setEditing(null)} onSave={(next) => { onSave?.(next); setEditing(null) }} />
  return <section className="era-manager"><header className="knowledge-toolbar"><div><p className="eyebrow">Cronologia</p><h2>Eras do universo</h2><p>As eras são páginas e também tags automáticas dos acontecimentos.</p></div>{onCreate && <button className="primary-button" onClick={onCreate}><Plus size={16} /> Nova era</button>}</header><div className="knowledge-grid">{eras.map((era) => <article className="knowledge-card era-card" key={era.id}><button onClick={() => onOpen?.(era)}><Clock3 size={30} style={{ color: era.accentColor || "var(--cyan)" }} /><strong>{era.title}</strong><small>{formatCalendarYears(era.eraStartYear ?? null, era.eraCalendar)} → {formatCalendarYears(era.eraEndYear ?? null, era.eraCalendar)}</small><small>{counts.get(era.id) ?? 0} acontecimentos</small></button><footer><button aria-label={`Editar era ${era.title}`} onClick={() => setEditing(era)}><Pencil size={14} /></button><button aria-label={`Excluir era ${era.title}`} onClick={() => onDelete?.(era.id)}><Trash2 size={14} /></button></footer></article>)}</div></section>
}

function EraForm({ era, onCancel, onSave }: { era: KnowledgePage; onCancel: () => void; onSave: (era: KnowledgePage) => void }) {
  const [draft, setDraft] = useState(era); const [start, setStart] = useState(era.eraStartYear == null ? "" : String(era.eraStartYear)); const [end, setEnd] = useState(era.eraEndYear == null ? "" : String(era.eraEndYear))
  return <form className="knowledge-editor era-form" onSubmit={(event) => { event.preventDefault(); const startYear = start.trim() ? parseCalendarYear(start) : null; const endYear = end.trim() ? parseCalendarYear(end) : null; if ((start.trim() && startYear == null) || (end.trim() && endYear == null)) return; onSave({ ...draft, title: draft.title.trim() || "Era sem nome", eraStartYear: startYear, eraEndYear: endYear, eraCalendar: draft.eraCalendar || "C.E.", updatedAt: Date.now() }) }}><header><h2>Editar era</h2></header><label><span>Nome</span><input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label><label><span>Resumo</span><textarea value={draft.summary} onChange={(event) => setDraft({ ...draft, summary: event.target.value })} /></label><div className="knowledge-editor-identity"><label><span>Ano inicial</span><input value={start} onChange={(event) => setStart(event.target.value)} placeholder="4027 C.E. ou 0 Logi" /></label><label><span>Ano final</span><input value={end} onChange={(event) => setEnd(event.target.value)} placeholder="Opcional" /></label><label><span>Calendário</span><select value={draft.eraCalendar ?? "C.E."} onChange={(event) => setDraft({ ...draft, eraCalendar: event.target.value })}><option>C.E.</option><option>Logi</option></select></label></div><footer><button type="button" onClick={onCancel}>Cancelar</button><button className="primary-button">Salvar era</button></footer></form>
}
